input_string = input("Enter elements of the first set separated by space: ")
set1 = set(input_string.split())
input_string2 = input("Enter the elements of the second set seperated by space : ")
set2 = set(input_string2.split())
set3 = set1.intersection(set2)
print(set3)
set4 = set1.union(set2)
print(set4)
set5 = set1.difference(set2)
print(set5)